# Generated by Django 3.1.6 on 2021-02-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='bus',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='academy',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='testsite',
            name='address_full',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='testsite',
            name='courseA',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='testsite',
            name='courseB',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='testsite',
            name='courseC',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='testsite',
            name='courseD',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='testsite',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
