# Generated by Django 3.1.6 on 2021-02-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0002_auto_20210204_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academy',
            old_name='url',
            new_name='academy_url',
        ),
        migrations.RenameField(
            model_name='testsite',
            old_name='url',
            new_name='testsite_url',
        ),
    ]
