# Generated by Django 3.1.6 on 2021-02-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0003_auto_20210204_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academy',
            old_name='academy_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='testsite',
            old_name='testsite_url',
            new_name='url',
        ),
    ]
