# Generated by Django 3.1.6 on 2021-02-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0004_auto_20210204_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='bus',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='academy',
            name='fee1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='academy',
            name='fee2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='academy',
            name='phone_number',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='academy',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
