# Generated by Django 3.1.6 on 2021-02-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0005_auto_20210204_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsite',
            name='courseA',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='testsite',
            name='courseB',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='testsite',
            name='courseC',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='testsite',
            name='courseD',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='testsite',
            name='phone_number',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='testsite',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
